name: C CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Debug info
      run: |
        echo "Current directory: $PWD"
        dir
        echo "PATH: $PATH"
        gcc --version

    - name: Build project
      run: |
        gcc -c utils.c -o utils.o
        gcc -c interface.c -o interface.o
        gcc -c screen.c -o screen.o
        gcc -c game.c -o game.o
        gcc -c input.c -o input.o
        gcc -c menu.c -o menu.o
        gcc -c sudoku.c -o sudoku.o
        gcc -static-libgcc -static-libstdc++ -static -o bgm utils.o interface.o screen.o game.o input.o menu.o sudoku.o
   
    - name: Archive artifact
      uses: actions/upload-artifact@v4
      with:
        name: artifact
        path: ./bgm.exe
