name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Debug info
      run: |
        echo "Current directory: $PWD"
        dir
        echo "PATH: $PATH"
        g++ --version

    - name: Build project
      run: |
        g++ -c utils.c -o utils.o
        g++ -c interface.c -o interface.o
        g++ -c screen.c -o screen.o
        g++ -c game.c -o game.o
        g++ -c input.c -o input.o
        g++ -c menu.c -o menu.o
        g++ -c sudoku.c -o sudoku.o
        g++ -static-libgcc -static-libstdc++ -static -o bgm utils.o interface.o screen.o game.o input.o menu.o sudoku.o
   
    - name: Archive artifact
      uses: actions/upload-artifact@v4
      with:
        name: artifact
        path: ./bgm.exe
